export {
  extractMarkdownImageAttachments,
  extractImageTagPaths,
  IMAGE_TAG_RE,
  IPC_CLOSE_SENTINEL,
  IPC_INPUT_SUBDIR,
  IPC_POLL_MS,
  normalizeAgentOutput,
  normalizeEjclawStructuredOutput,
  normalizePublicTextOutput,
  OUTPUT_END_MARKER,
  OUTPUT_START_MARKER,
  writeProtocolOutput,
  type NormalizedRunnerOutput,
  type NormalizedAgentOutput,
  type RunnerOutputAttachment,
  type RunnerOutputPhase,
  type RunnerOutputVerdict,
  type RunnerOutputVisibility,
  type RunnerStructuredOutput,
} from 'ejclaw-runners-shared';
